language: csharp
solution: SemanticVersionEnforcer.sln
install:
  - nuget restore SemanticVersionEnforcer.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SemanticVersionEnforcer.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SemanticVersionEnforcer.Tests/bin/Release/SemanticVersionEnforcer.Tests.dll